# i3blocks configuration file

# Global properties
separator=true
separator_block_width=20

[none]
full_text= 
interval=once

[sher_noob]
full_text=Sher - Noob
interval=once

[window_title]
full_text= 
background=#4a4a56
min_width=1000
command=~/.config/i3/scripts/xtitle.sh
interval=persist

[bright]
command=~/.config/i3/scripts/status/bright.sh
interval=once
signal=1

[pin]
command=~/.config/i3/scripts/status/pin.sh
interval=10

[volume]
command=~/.config/i3/scripts/status/volume.sh
interval=once
signal=2

[time]
command=~/.config/i3/scripts/status/time.sh
interval=30
